//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const HOME_ENABLE_LOADER = 'HOME_ENABLE_LOADER';
export const HOME_DISABLE_LOADER = 'HOME_DISABLE_LOADER';
export const GET_CHAT_ENABLE_LOADER = 'GET_CHAT_ENABLE_LOADER';
export const GET_CHAT_DISABLE_LOADER = 'GET_CHAT_DISABLE_LOADER';
export const GET_CHAT_DETAIL_ENABLE_LOADER = 'GET_CHAT_DETAIL_ENABLE_LOADER';
export const GET_CHAT_DETAIL_DISABLE_LOADER = 'GET_CHAT_DETAIL_DISABLE_LOADER';
export const GET_ALL_STUDENT_ENABLE_LOADER = 'GET_ALL_STUDENT_ENABLE_LOADER';
export const GET_ALL_STUDENT_DISABLE_LOADER = 'GET_ALL_STUDENT_DISABLE_LOADER';
export const STUDENT_FEED_ENABLE_LOADER = 'STUDENT_FEED_ENABLE_LOADER';
export const STUDENT_FEED_DISABLE_LOADER = 'STUDENT_FEED_DISABLE_LOADER';
export const GET_ALL_USER_ADDED_ENABLE_LOADER = 'GET_ALL_USER_ADDED_ENABLE_LOADER';
export const GET_ALL_USER_ADDED_DISABLE_LOADER = 'GET_ALL_USER_ADDED_DISABLE_LOADER';
export const GET_EARNINGS_LIST_ENABLE_LOADER = 'GET_EARNINGS_LIST_ENABLE_LOADER';
export const GET_EARNINGS_LIST_DISABLE_LOADER = 'GET_EARNINGS_LIST_DISABLE_LOADER';
export const REGISTER_ENABLE_LOADER = 'REGISTER_ENABLE_LOADER';
export const REGISTER_DISABLE_LOADER = 'REGISTER_DISABLE_LOADER';
export const EDIT_PROFILE_ENABLE_LOADER = 'EDIT_PROFILE_ENABLE_LOADER';
export const EDIT_PROFILE_DISABLE_LOADER = 'EDIT_PROFILE_DISABLE_LOADER';
export const EDIT_POST_ENABLE_LOADER = 'EDIT_POST_ENABLE_LOADER';
export const EDIT_POST_DISABLE_LOADER = 'EDIT_POST_DISABLE_LOADER';
export const GET_COMMENTS_ENABLE_LOADER = 'GET_COMMENTS_ENABLE_LOADER';
export const GET_COMMENTS_DISABLE_LOADER = 'GET_COMMENTS_DISABLE_LOADER';
export const NOTIFICATIONLIST_ENABLE_LOADER= 'NOTIFICATIONLIST_ENABLE_LOADER';
export const NOTIFICATIONLIST_DISABLE_LOADER ='NOTIFICATIONLIST_DISABLE_LOADER';
export const FOLLOWERS_LIST_ENABLE_LOADER = 'FOLLOWERS_LIST_ENABLE_LOADER';
export const FOLLOWERS_LIST_DISABLE_LOADER = 'FOLLOWERS_LIST_DISABLE_LOADER';
export const FOLLOWINGS_LIST_ENABLE_LOADER = 'FOLLOWINGS_LIST_ENABLE_LOADER';
export const FOLLOWINGS_LIST_DISABLE_LOADER = 'FOLLOWINGS_LIST_DISABLE_LOADER';
export const DELETE_POST_ENABLE_LOADER = 'DELETE_POST_ENABLE_LOADER';
export const DELETE_POST_DISABLE_LOADER = 'DELETE_POST_DISABLE_LOADER';
export const DELETE_HOME_POST_ENABLE_LOADER = 'DELETE_HOME_POST_ENABLE_LOADER';
export const DELETE_HOME_POST_DISABLE_LOADER = 'DELETE_HOME_POST_DISABLE_LOADER';
export const NETWORK_INFO_STATUS='NETWORK_INFO_STATUS';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_RESPONSE = 'LOGOUT_RESPONSE';
export const LOGIN_RESET = 'LOGIN_RESET';


//home items
export const HOME_REQUEST = 'HOME_REQUEST';
export const HOME_RESPONSE = 'HOME_RESPONSE';
export const HOME_FAILED = 'HOME_FAILED';
export const HOME_LIKE_EDITED='HOME_LIKE_EDITED';

//get all student
export const GET_ALL_STUDENT_REQUEST = 'GET_ALL_STUDENT_REQUEST';
export const GET_ALL_STUDENT_RESPONSE = 'GET_ALL_STUDENT_RESPONSE';
export const GET_ALL_STUDENT_FAILED = 'GET_ALL_STUDENT_FAILED';

//get all user added post
export const GET_ALL_USER_ADDED_POST_REQUEST = 'GET_ALL_USER_ADDED_POST_REQUEST';
export const GET_ALL_USER_ADDED_POST_RESPONSE = 'GET_ALL_USER_ADDED_POST_RESPONSE';
export const GET_ALL_USER_ADDED_POST_FAILED = 'GET_ALL_USER_ADDED_POST_FAILED';

//like post
export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_RESPONSE = 'LIKE_POST_RESPONSE';
export const LIKE_POST_FAILED = 'LIKE_POST_FAILED';
export const LIKE_POST_SUCESS = 'LIKE_POST_SUCESS';
export const LIKE_POST_STUDENT_SUCESS = 'LIKE_POST_STUDENT_SUCESS';


//unlike post_id
export const UNLIKE_POST_REQUEST = 'UNLIKE_POST_REQUEST';
export const UNLIKE_POST_RESPONSE = 'UNLIKE_POST_RESPONSE';
export const UNLIKE_POST_FAILED = 'UNLIKE_POST_FAILED';
export const UNLIKE_POST_SUCESS = 'UNLIKE_POST_SUCESS';
export const UNLIKE_POST_STUDENT_SUCESS = 'UNLIKE_POST_STUDENT_SUCESS';

//student list like post 
export const STUDENT_LIKE_POST_REQUEST = 'STUDENT_LIKE_POST_REQUEST';
export const STUDENT_LIKE_POST_RESPONSE = 'STUDENT_LIKE_POST_RESPONSE';
export const STUDENT_LIKE_POST_FAILED = 'STUDENT_LIKE_POST_FAILED';
export const STUDENT_LIKE_POST_SUCESS = 'STUDENT_LIKE_POST_SUCESS';

//student list unlike post 
export const STUDENT_UNLIKE_POST_REQUEST = 'STUDENT_UNLIKE_POST_REQUEST';
export const STUDENT_UNLIKE_POST_RESPONSE = 'STUDENT_UNLIKE_POST_RESPONSE';
export const STUDENT_UNLIKE_POST_FAILED = 'STUDENT_UNLIKE_POST_FAILED';
export const STUDENT_UNLIKE_POST_SUCESS = 'STUDENT_UNLIKE_POST_SUCESS';

//myhome like post
export const MY_HOME_LIKE_POST_REQUEST = 'MY_HOME_LIKE_POST_REQUEST';
export const MY_HOME_LIKE_POST_RESPONSE = 'MY_HOME_LIKE_POST_RESPONSE';
export const MY_HOME_LIKE_POST_FAILED = 'MY_HOME_LIKE_POST_FAILED';
export const MY_HOME_LIKE_POST_SUCESS = 'MY_HOME_LIKE_POST_SUCESS';


//myhome unlike post_id
export const MY_HOME_UNLIKE_POST_REQUEST = 'MY_HOME_UNLIKE_POST_REQUEST';
export const MY_HOME_UNLIKE_POST_RESPONSE = 'MY_HOME_UNLIKE_POST_RESPONSE';
export const MY_HOME_UNLIKE_POST_FAILED = 'MY_HOME_UNLIKE_POST_FAILED';
export const MY_HOME_UNLIKE_POST_SUCESS = 'MY_HOME_UNLIKE_POST_SUCESS';

//edit user profile
export const EDIT_USER_PROFILE_REQUEST = 'EDIT_USER_PROFILE_REQUEST';
export const EDIT_USER_PROFILE_RESPONSE = 'EDIT_USER_PROFILE_RESPONSE';
export const EDIT_USER_PROFILE_FAILED = 'EDIT_USER_PROFILE_FAILED';

//get all chat list
export const GET_CHAT_LIST_REQUEST = 'GET_CHAT_LIST_REQUEST';
export const GET_CHAT_LIST_RESPONSE = 'GET_CHAT_LIST_RESPONSE';
export const GET_CHAT_LIST_FAILED = 'GET_CHAT_LIST_FAILED';

//get chat detail
export const GET_CHAT_DETAIL_REQUEST = 'GET_CHAT_DETAIL_REQUEST';
export const GET_CHAT_DETAIL_RESPONSE = 'GET_CHAT_DETAIL_RESPONSE';
export const GET_CHAT_DETAIL_FAILED = 'GET_CHAT_DETAIL_FAILED';

//send message
export const SEND_CHAT_REQUEST = 'SEND_CHAT_REQUEST';
export const SEND_CHAT_RESPONSE = 'SEND_CHAT_RESPONSE';
export const SEND_CHAT_FAILED = 'SEND_CHAT_FAILED';
export const SEND_CHAT_SUCESS = 'SEND_CHAT_SUCESS'

//add post image
export const ADD_POST_IMAGE_REQUEST = 'ADD_POST_IMAGE_REQUEST';
export const ADD_POST_IMAGE_RESPONSE = 'ADD_POST_IMAGE_RESPONSE';
export const ADD_POST_IMAGE_FAILED = 'ADD_POST_IMAGE_FAILED';
export const ADD_POST_IMAGE_SUCESS = 'ADD_POST_IMAGE_SUCESS'


//add video image
export const ADD_POST_VIDEO_REQUEST = 'ADD_POST_VIDEO_REQUEST';
export const ADD_POST_VIDEO_RESPONSE = 'ADD_POST_VIDEO_RESPONSE';
export const ADD_POST_VIDEO_FAILED = 'ADD_POST_VIDEO_FAILED';
export const ADD_POST_VIDEO_SUCESS = 'ADD_POST_VIDEO_SUCESS'

//student feed
export const STUDENT_FEED_REQUEST = 'STUDENT_FEED_REQUEST';
export const STUDENT_FEED_RESPONSE = 'STUDENT_FEED_RESPONSE';
export const STUDENT_FEED_FAILED = 'STUDENT_FEED_FAILED';

//forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_RESPONSE = 'FORGOT_PASSWORD_RESPONSE';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

//earnings list
export const GET_EARNINGS_LIST_REQUEST = 'GET_EARNINGS_LIST_REQUEST';
export const GET_EARNINGS_LIST_RESPONSE = 'GET_EARNINGS_LIST_RESPONSE';
export const GET_EARNINGS_LIST__FAILED = 'GET_EARNINGS_LIST__FAILED';

//register user
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_TOKEN_UPDATE = 'REGISTER_TOKEN_UPDATE';

//edit profile user
export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_RESPONSE = 'EDIT_PROFILE_RESPONSE';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';
export const EDIT_PROFILE_UPDATE = 'EDIT_PROFILE_UPDATE';

//user details
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_RESPONSE = 'USER_DETAILS_RESPONSE';
export const USER_DETAILS_FAILED = 'USER_DETAILS_FAILED';


//add bank details
export const ADD_BANK_DETAILS_REQUEST = 'ADD_BANK_DETAILS_REQUEST';
export const ADD_BANK_DETAILS_RESPONSE = 'ADD_BANK_DETAILS_RESPONSE';
export const ADD_BANK_DETAILS_FAILED = 'ADD_BANK_DETAILS_FAILED';

//get comments
export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_RESPONSE = 'GET_COMMENTS_RESPONSE';
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED';

// get all countries
export const GET_COUNTRIES_REQUEST = 'GET_COUNTRIES_REQUEST';
export const GET_COUNTRIES_RESPONSE = 'GET_COUNTRIES_RESPONSE';
export const GET_COUNTRIES_FAILED = 'GET_COUNTRIES_FAILED';

//get all states
export const GET_STATES_REQUEST = 'GET_STATES_REQUEST';
export const GET_STATES_RESPONSE = 'GET_STATES_RESPONSE';
export const GET_STATES_FAILED = 'GET_STATES_FAILED';

//report admin
export const REPORT_ADMIN_REQUEST = 'REPORT_ADMIN_REQUEST';
export const REPORT_ADMIN_RESPONSE = 'REPORT_ADMIN_RESPONSE';
export const REPORT_ADMIN_FAILED = 'REPORT_ADMIN_FAILED';

//request payment
export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_RESPONSE = 'PAYMENT_RESPONSE';
export const PAYMENT_FAILED = 'PAYMENT_FAILED';

//get all payment
export const ALL_PAYMENT_REQUEST = 'ALL_PAYMENT_REQUEST';
export const ALL_PAYMENT_RESPONSE = 'ALL_PAYMENT_RESPONSE';
export const ALL_PAYMENT_FAILED = 'ALL_PAYMENT_FAILED';

//notifications list
export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST';
export const GET_NOTIFICATION_RESPONSE = 'GET_NOTIFICATION_RESPONSE';
export const GET_NOTIFICATION_FAILED = 'GET_NOTIFICATION_FAILED';

//notifications read
export const READ_NOTIFICATION_REQUEST = 'READ_NOTIFICATION_REQUEST';
export const READ_NOTIFICATION_RESPONSE = 'READ_NOTIFICATION_RESPONSE';
export const READ_NOTIFICATION_FAILED = 'READ_NOTIFICATION_FAILED';

//comment post
export const COMMENT_POST_REQUEST = 'COMMENT_POST_REQUEST';
export const COMMENT_POST_RESPONSE = 'COMMENT_POST_RESPONSE';
export const COMMENT_POST_FAILED = 'COMMENT_POST_FAILED';
export const COMMENT_POST_SUCESS = 'COMMENT_POST_SUCESS';

//add text feed
export const TEXT_FEED_REQUEST = 'TEXT_FEED_REQUEST';
export const TEXT_FEED_RESPONSE = 'TEXT_FEED_RESPONSE';
export const TEXT_FEED_FAILED = 'TEXT_FEED_FAILED';
export const TEXT_FEED_SUCESS = 'TEXT_FEED_SUCESS';

//change password
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_RESPONSE = 'CHANGE_PASSWORD_RESPONSE';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

//followers list
export const FOLLOWERS_LIST_REQUEST = 'FOLLOWERS_LIST_REQUEST';
export const FOLLOWERS_LIST_RESPONSE = 'FOLLOWERS_LIST_RESPONSE';
export const FOLLOWERS_LIST_FAILED = 'FOLLOWERS_LIST_FAILED';

//followings list
export const FOLLOWINGS_LIST_REQUEST = 'FOLLOWINGS_LIST_REQUEST';
export const FOLLOWINGS_LIST_RESPONSE = 'FOLLOWINGS_LIST_RESPONSE';
export const FOLLOWINGS_LIST_FAILED = 'FOLLOWINGS_LIST_FAILED';

//suggestions list
export const SUGGESTIONS_LIST_REQUEST = 'SUGGESTIONS_LIST_REQUEST';
export const SUGGESTIONS_LIST_RESPONSE = 'SUGGESTIONS_LIST_RESPONSE';
export const SUGGESTIONS_LIST_FAILED = 'SUGGESTIONS_LIST_FAILED';

//delete post
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_RESPONSE = 'DELETE_POST_RESPONSE';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';
export const DELETE_POST_SUCESS = 'DELETE_POST_SUCESS';

//delete home post
export const DELETE_HOME_POST_REQUEST = 'DELETE_HOME_POST_REQUEST';
export const DELETE_HOME_POST_RESPONSE = 'DELETE_HOME_POST_RESPONSE';
export const DELETE_HOME_POST_FAILED = 'DELETE_HOME_POST_FAILED';
export const DELETE_HOME_POST_SUCESS = 'DELETE_HOME_POST_SUCESS';

//follow student
export const FOLLOW_STUDENT_REQUEST = 'FOLLOW_STUDENT_REQUEST';
export const FOLLOW_STUDENT_RESPONSE = 'FOLLOW_STUDENT_RESPONSE';
export const FOLLOW_STUDENT_FAILED = 'FOLLOW_STUDENT_FAILED';
export const FOLLOW_STUDENT_SUCESS = 'FOLLOW_STUDENT_SUCESS';

//unfollow student
export const UNFOLLOW_STUDENT_REQUEST = 'UNFOLLOW_STUDENT_REQUEST';
export const UNFOLLOW_STUDENT_RESPONSE = 'UNFOLLOW_STUDENT_RESPONSE';
export const UNFOLLOW_STUDENT_FAILED = 'UNFOLLOW_STUDENT_FAILED';
export const UNFOLLOW_STUDENT_SUCESS= 'UNFOLLOW_STUDENT_SUCESS';

//follow 
export const FOLLOW_REQUEST = 'FOLLOW_REQUEST';
export const FOLLOW_RESPONSE = 'FOLLOW_RESPONSE';
export const FOLLOW_FAILED = 'FOLLOW_FAILED';
export const FOLLOW_SUCESS = 'FOLLOW_SUCESS';

//unfollow 
export const UNFOLLOW_REQUEST = 'UNFOLLOW_REQUEST';
export const UNFOLLOW_RESPONSE = 'UNFOLLOW_RESPONSE';
export const UNFOLLOW_FAILED = 'UNFOLLOW_FAILED';
export const UNFOLLOW_SUCESS= 'UNFOLLOW_SUCESS';

//follow suggest
export const FOLLOW_SUGGEST_REQUEST = 'FOLLOW_SUGGEST_REQUEST';
export const FOLLOW_SUGGEST_RESPONSE = 'FOLLOW_SUGGEST_RESPONSE';
export const FOLLOW_SUGGEST_FAILED = 'FOLLOW_SUGGEST_FAILED';
export const FOLLOW_SUGGEST_SUCESS = 'FOLLOW_SUGGEST_SUCESS';


//edit Post user
export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const EDIT_POST_RESPONSE = 'EDIT_POST_RESPONSE';
export const EDIT_POST_FAILED = 'EDIT_POST_FAILED';
export const EDIT_POST_UPDATE = 'EDIT_POST_UPDATE';