/* App config for apis
 */
const ApiConstants = {
    BASE_URL: 'http://edumetrix.io/',
    LOGIN: 'api/mobileapi/student/login',
    HOME:'api/mobileapi/newsfeed/get_home_items',
    GETSTUDENT:'api/mobileapi/student/getAllStudents',
    GETUSERPOST:'api/mobileapi/newsfeed/get_all_my_added_post',
    LIKEPOST:'api/mobileapi/newsfeed/like_post',
    GETCHATLIST:'api/mobileapi/newsfeed/get_all_my_chats',
    GETCHATDETAIL:'api/mobileapi/newsfeed/get_all_my_chat_details',
    SENDMESSAGE:'api/mobileapi/newsfeed/send_chat_message',
    STUDENTFEED:'api/mobileapi/newsfeed/get_all_students_added_post',
    FORGOTPASSWORD:'api/mobileapi/student/forgotPassword',
    GETEARNINGSLIST:'api/mobileapi/student/getMyEarningDetails',
    REGISTER:'api/mobileapi/student/registration',
    EDITPROFILE:'api/mobileapi/student/editProfileUserDetails',
    USERDETAILS:'api/mobileapi/student/getMyProfileUserDetails',
    ADDBANK:'api/mobileapi/student/add_bank_details',
    GETCOMMENTS:'api/mobileapi/newsfeed/get_post_comments',
    GETSTATE:'api/mobileapi/student/get_states',
    GETCOUNTRY:'api/mobileapi/student/get_countries',
    REPORTADMIN:'api/mobileapi/newsfeed/report_post',
    REQUESTPAYMENT:'api/mobileapi/student/request_payment',
    GETALLPAYMENT:'api/mobileapi/student/get_all_my_payment_request',
    NOTIFICATIONLIST:'api/mobileapi/newsfeed/get_all_my_notifications',
    READNOTIFICATION:'api/mobileapi/newsfeed/clear_notifications',
    COMMENTPOST:'api/mobileapi/newsfeed/comment_post',
    TEXTFEED:'api/mobileapi/newsfeed/add_post_text',
    UNLIKEPOST:'api/mobileapi/newsfeed/unlike_post',
    ADDPOSTIMAGE:'api/mobileapi/newsfeed/add_post_image',
    ADDPOSTVIDEO:'api/mobileapi/newsfeed/add_post_video',
    CHANGEPASSWORD:'api/mobileapi/student/changePassword',
    FOLLOWERSLIST:'api/mobileapi/newsfeed/get_all_my_followers',
    FOLLOWINGSLIST:'api/mobileapi/newsfeed/get_all_my_followings',
    SUGGESTIONSLIST:'api/mobileapi/newsfeed/get_all_my_suggestions',
    DELETEPOST:'api/mobileapi/newsfeed/delete_post',
    FOLLOWSTUDENT:'api/mobileapi/newsfeed/follow_student',
    UNFOLLOWSTUDENT:'api/mobileapi/newsfeed/unfollow_student',
    EDITPOST:'api/mobileapi/newsfeed/edit_post_text',

};

export default ApiConstants;
