# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EduMetrix' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EduMetrix
 `pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'`

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'EduMetrixTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EduMetrix-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EduMetrix-tvOS

 
end
